# Generated by Django 5.0 on 2023-12-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=10)),
                ('auteur', models.CharField(max_length=10)),
                ('datePublication', models.DateField()),
                ('image', models.ImageField(upload_to='image_livre/')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField()),
            ],
        ),
    ]
